name: owasp dependency check
on:
  schedule:
   - cron: '0 5 * * *' # Runs daily at 5 AM UTC
  workflow_dispatch: #allow manual trigger

permissions:
  contents: read
jobs:
  depCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: SPANDigital/span-github-actions/.github/actions/owasp-dependency-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
